export const FETCH_FEED_DATA = 'FETCH_FEED_DATA';
export const UPDATE_FEED_DATA = 'UPDATE_FEED_DATA';
export const RESPECT_WORKOUT = 'RESPECT_WORKOUT';
export const UNRESPECT_WORKOUT = 'UNRESPECT_WORKOUT';
export const LOADING_START = 'LOADING_START';
export const LOADING_FINISHED = 'LOADING_FINISHED';
